language: node_js
node_js:
  - "lts/*"

notifications:
  email: false

env:
  global:
    secure: "CF6TPrktMi4Vxw+rjQel82Wo8mNeBss8eEKR33b6zGDCye/YXOyYpuPwVU6QHSaFaG4AmDnCsO30jaKfTiJlwkrnTMB/CswnQaKbsiZjZLPdscUTIYpeza6pLhc6ehGSryp6St4ow5ZOxKdZ5/SqEm+bLppoeOrOCZeCHKEhRqKU+u/QqlbsJOUerMo2CNTSxpMp+eOeaJFKbHgBtlUZaLeOieKye6dsLxvRHHcNDEiPy1w3CUtWPAWvHv2IHV1Qo63+b6HfnUQipr/EZMvyByDkmKj1JcxAYCbqeIACmysP9vu9EenB+Wwgl2Iqr+c6nnrrO69rVz3EB+JiyQD7TimtjRvLpMtN0+tnA/+VUJh2w4kqtdIic64zIx7tse0nQ2fExPNegigBY4use2cQyaTC939VXzhtcEv7uKk83qpJ25tjpxpAPI97+We+WpKibUT8cxhOrt9RT+pUyCxaXmEMvhWu6RU6s3nLTKx5xYMp1NLjagz3+WLOXT9kwGAG2xCEIKJz40ePrhm+MxrDN+j8PEXBFHYZMWU6ScT1cmUAg88CtjmnTPOeO/I2i9kWwfSsxjfII4t+L71V3JX6udNjp93km14ZbiUwZjGBB+zUk8vCMgso1lI79k4MSaufje6g0wkkDid7TS63uaWhO9/4YckNsVOPb7ANdG5crmQ="
    
